exchanges:
  binance:
    type: binance
    kind: spot
#    key: xlkxhcUyhybRnqkfFMES6X1iHMlcyTc0w0YPnbi1lx7hNhDjCxz1GjholCumEZyX
#    secret: TLv5V4ZTeZ5R0GRg8vixCrbK63l2lzsqAMj0uYkcMTY02HVC2fwN6QpUSsnJHIhL
    key: joWeHq25THzSbBhbOPUociphPz5jWB61dG8T0s87Yd3eGl9D8C4vlNZyZCbDKqRS
    secret: ijKwYGtDQUNRIWxHyBxTodX8qcqkfvfYROIY9BWn6IQzSpo9Ivo52XunxbM2gdIm
    timeout: 30s
db:
  type: mysql
  #uri: root:super123456@tcp(192.168.0.3:3306)/exchange
  uri: root:123456@tcp(10.100.100.2:3306)/exchange


# cert:
#   ca: perm/ca.crt
#   cert: perm/server.crt
#   key: perm/server.key
# mode: full
# name: trendtracking

#proxy: socks5://127.0.0.1:1080

  # url: http://192.168.0.248:19088
  # id: afuturestar
  # id: 34528553395@chatroom
